### ISSUE TITLE
Requires CUDA 8

### ISSUE THREAD

**Issue by brannondorsey** [brannondorsey/PassGAN#15]
This implementation requires CUDA 8. If CUDA 9 or greater is installed an error similar to the one below will be thrown. I've received questions about this via email, so I've created this issue for future reference. I've also updated the README to specify CUDA 8 is required.

```
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    import tensorflow as tf
  File "/home/bf/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/bf/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/bf/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/bf/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/bf/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/bf/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by brannondorsey** [comment]
CUDA 8 will remain the required CUDA version. At least for the time being.

**Comment by NovaBlastHD** [comment]
Tensorflow (or Tensorflow-gpu) has to be updated to run with the latest CUDA.
