### ISSUE TITLE
How to train model with LinkedIn leak ?

### ISSUE THREAD

**Issue by semeniak1997** [brannondorsey/PassGAN#16]
I unpacked the "LinkedIn leak" archive into the "/data" directory and renamed it to train.txt. Launched with the following command:
`python3 train.py --output-dir output --training-data data/train.txt`
And throws the following error:

loaded 0 lines in dataset
Traceback (most recent call last):
  File "train.py", line 99, in <module>
    fake_inputs = models.Generator(args.batch_size, args.seq_length, args.layer_dim, len(charmap))
  File "/share/home/nikita/rd/PassGAN/models.py", line 24, in Generator
    output = tf.transpose(output, [0, 2, 1])
  File "/home/nikita/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1336, in transpose
    ret = gen_array_ops.transpose(a, perm, name=name)
  File "/home/nikita/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5694, in transpose
    "Transpose", x=x, perm=perm, name=name)
  File "/home/nikita/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/nikita/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/home/nikita/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/nikita/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/nikita/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/nikita/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension must be 2 but is 3 for 'transpose' (op: 'Transpose') with input shapes: [64,10], [3].

**P.S. sample rockyou traind successful**

**Comment by Broimlookingforcode** [comment]
I thing there might be another txt called train, call it smth else and change train in command to watever u called it
