### ISSUE TITLE
Conv2DCustomBackpropFilterOp only supports NHWC

### ISSUE THREAD

**Issue by odien6** [brannondorsey/PassGAN#7]
Hi,
When I'm trying to run PassGAN model there is an error:
_2018-01-21 19:45:25.121447: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: Conv2DCustomBackpropFilterOp only supports NHWC.
	 [[Node: gradients_2/Discriminator.5.2/conv1d/Conv2D_grad/Conv2DBackpropFilter = Conv2DBackpropFilter[T=DT_FLOAT, data_format="NCHW", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Discriminator.5.2/conv1d/ExpandDims, gradients_2/Discriminator.5.2/conv1d/Conv2D_grad/ShapeN:1, gradients_2/Discriminator.5.2/conv1d/Squeeze_grad/Reshape)]]_

Cuda and tensorflow-gpu are working correctly, I verified this for example by running CUDNN minimal deep learning training code sample using LeNet (https://github.com/tbennun/cudnn-training), no issues there.

After changing data format from NCHW to NHWC in files: batchnorm.py, conv1d.py and conv2d.py I have got another error:
_ValueError: Dimensions must be equal, but are 10 and 128 for 'Generator.1.1/conv1d/Conv2D' (op: 'Conv2D') with input shapes: [64,1,128,10], [1,5,128,128]._

Is anybody have the same issue? Any ideas about what is wrong and how to solve it?
BTW. solution from closed issue (https://github.com/brannondorsey/PassGAN/issues/3) did not work for me...

PC details:
Linux Mint 18.3
Intel i7-8700K
Titan X(Pascal)
Nvidia drivers: 390.12

Setup details:
**nvcc -V**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

**cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2**
#define CUDNN_MAJOR      6
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 21
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
#include "driver_types.h

**Comment by bpartin2009** [comment]
So did you uninstall tensorflow? Just leaving tensorflow-gpu?
I have both installed but it seems to want to run only on CPU right now....

I tried to "pip uninstall tensorflow-1.7.0-cp27-cp27mu-manylinux1_x86_64.whl" but when I tried to run PassGAN it says that there is no tensforflow module to import as tf.

bash-4.2$ python sample.py --input-dir pretrained --checkpoint pretrained/checkpoints/195000.ckpt --output gen_words.txt --batch-size 1024 --num-samples 1000000
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
WARNING:tensorflow:From /scratch/PassGAN/PassGAN-master/tflib/ops/conv1d.py:93: calling conv1d (from tensorflow.python.ops.nn_ops) with data_format=NCHW is deprecated and will be removed in a future version.
Instructions for updating:
`NCHW` for data_format is deprecated, use `NCW` instead
2018-04-23 08:25:50.869772: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "sample.py", line 108, in <module>
    samples.extend(generate_samples())
  File "sample.py", line 84, in generate_samples
    samples = session.run(fake_inputs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: Generic conv implementation only supports NHWC tensor format for now.
         [[Node: Generator.1.1/conv1d/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Generator.1.1/conv1d/ExpandDims, Generator.1.1/conv1d/ExpandDims_1)]]

Caused by op u'Generator.1.1/conv1d/Conv2D', defined at:
  File "sample.py", line 79, in <module>
    fake_inputs = models.Generator(args.batch_size, args.seq_length, args.layer_dim, len(charmap))
  File "/scratch/PassGAN/PassGAN-master/models.py", line 18, in Generator
    output = ResBlock('Generator.1', output, layer_dim)
  File "/scratch/PassGAN/PassGAN-master/models.py", line 9, in ResBlock
    output = lib.ops.conv1d.Conv1D(name+'.1', dim, dim, 5, output)
  File "/scratch/PassGAN/PassGAN-master/tflib/ops/conv1d.py", line 93, in Conv1D
    data_format='NCHW'
  File "/usr/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 497, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 497, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 2466, in conv1d
    data_format=data_format)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 953, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): Generic conv implementation only supports NHWC tensor format for now.
         [[Node: Generator.1.1/conv1d/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Generator.1.1/conv1d/ExpandDims, Generator.1.1/conv1d/ExpandDims_1)]]

PC details:
Linux RHEL 7.3
Intel Xeon
Telsa K40
Nvidia drivers: 384.81

Setup details:
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
